StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65EC77356C48CD50}" {
   Id "PDV_FirstRocketBlock_Mi8"
   Target_en_us "First Rocket Block"
   Target_fr_fr "Premier bloc de roquettes"
   Target_it_it "Primo blocco razzi"
   Target_de_de "Erster Raketenblock"
   Target_es_es "Primer bloque de cohetes"
   Target_cs_cz "První raketový blok"
   Target_pl_pl "Pierwszy blok rakietowy"
   Target_ru_ru "Первый ракетный блок"
   Target_ja_jp "最初のロケットブロック"
   Target_ko_kr "첫 번째 로켓 블록"
   Target_pt_br "Primeiro bloco de foguetes"
   Target_zh_cn "第一个火箭模块"
   Target_uk_ua "Перший ракетний блок"
   Modified 1709996527
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65EC7735AE895C3B}" {
   Id "PDV_SecondRocketBlock_Mi8"
   Target_en_us "Second Rocket Block"
   Target_fr_fr "Deuxième bloc de roquettes"
   Target_it_it "Secondo blocco razzi"
   Target_de_de "Zweiter Raketenblock"
   Target_es_es "Segundo bloque de cohetes"
   Target_cs_cz "Druhý raketový blok"
   Target_pl_pl "Drugi blok rakietowy"
   Target_ru_ru "Второй ракетный блок"
   Target_ja_jp "第二のロケットブロック"
   Target_ko_kr "두 번째 로켓 블록"
   Target_pt_br "Segundo bloco de foguetes"
   Target_zh_cn "第二个火箭模块"
   Target_uk_ua "Другий ракетний блок"
   Modified 1709996537
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65EC7735B6079BB6}" {
   Id "PDV_ThirdRocketBlock_Mi8"
   Target_en_us "Third Rocket Block"
   Target_fr_fr "Troisième bloc de roquettes"
   Target_it_it "Terzo blocco razzi"
   Target_de_de "Dritter Raketenblock"
   Target_es_es "Tercer bloque de cohetes"
   Target_cs_cz "Třetí raketový blok"
   Target_pl_pl "Trzeci blok rakietowy"
   Target_ru_ru "Третий ракетный блок"
   Target_ja_jp "第三のロケットブロック"
   Target_ko_kr "세 번째 로켓 블록"
   Target_pt_br "Terceiro bloco de foguetes"
   Target_zh_cn "第三个火箭模块"
   Target_uk_ua "Третій ракетний блок"
   Modified 1709996553
   Author "hasta"
   LastChanged "hasta"
  }
 }
}