SCR_EntityCatalogMultiList : "{3B679F1799D55F6F}Configs/EntityCatalog/USSR/Characters_EntityCatalog_USSR.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6126B736FAA4BEEB}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6126B736FFC0EC1C}" {
     m_sEntityPrefab "{A6E6C7AF25DDF502}Prefabs/Characters/Campaign/ru_army/desert/Campaign_USSR_Player_Podval_Desert_new_randomized.et"
    }
   }
  }
 }
}