SCR_EntityCatalogMultiList : "{3B679F1799D55F6F}Configs/EntityCatalog/USSR/Characters_EntityCatalog_USSR.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6126B736FAA4BEEB}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6126B736FFC0EC1C}" {
     m_sEntityPrefab "{0914C08E274E7C93}Prefabs/Characters/Campaign/ru_army/desert/Campaign_USSR_Player_Podval_Desert2_new.et"
    }
    SCR_EntityCatalogEntry "{6126B736FE8FDB25}" {
     m_sEntityPrefab "{6759FED7122F921B}Prefabs/Characters/Campaign/ru_army/desert/Campaign_USSR_Player_Podval_Desert3_new.et"
    }
    SCR_EntityCatalogEntry "{661949726DFB6419}" {
     m_sEntityPrefab "{2E4AA4B331E02D30}Prefabs/Characters/Campaign/ru_army/desert/Campaign_USSR_Player_Podval_Desert4_new.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A4686C031}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
    SCR_EntityCatalogEntry "{6619497269A40619}" {
     m_sEntityPrefab "{9B6295F60FC669C4}Prefabs/Characters/Campaign/ru_army/desert/Campaign_USSR_Player_Podval_Desert_new.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A423A75FB}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
    SCR_EntityCatalogEntry "{661949774C85EC99}" {
     m_sEntityPrefab "{B77CFDC28088D711}Prefabs/Characters/Campaign/ru_army/Campaign_USSR_Player_Podval_new.et"
    }
    SCR_EntityCatalogEntry "{6619497749AE2316}" {
     m_sEntityPrefab "{3B8430877E1DC7B7}Prefabs/Characters/Campaign/ru_army/Campaign_USSR_Player_Podval_new2.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A7DF2F845}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
    SCR_EntityCatalogEntry "{661949774778CBA9}" {
     m_sEntityPrefab "{DE187C7E72F850DC}Prefabs/Characters/Campaign/ru_army/Campaign_USSR_Player_Podval_new3.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A7937289B}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
    SCR_EntityCatalogEntry "{66194977443F4D1C}" {
     m_sEntityPrefab "{E32C59460794D9EB}Prefabs/Characters/Campaign/ru_army/Campaign_USSR_Player_Podval_new4.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A72A3B369}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
    SCR_EntityCatalogEntry "{661949774196419D}" {
     m_sEntityPrefab "{38F9146B99916440}Prefabs/Characters/Campaign/ru_army/Campaign_USSR_Player_Podval_new5.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{6619497A6E0AFCD9}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
   }
  }
 }
}