SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{650E8E2E00FB1C0C}" {
   m_sIdentifier "Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{650E8E2EF7A4B114}" {
     m_sEntityPrefab "{16A674FE31B0921C}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_uncovered.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F486C1803290}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247326389CD3ED}" {
       m_eSlotTypes 24
      }
     }
    }
    SCR_EntityCatalogEntry "{650E8E2EF0218F2C}" {
     m_sEntityPrefab "{16A674FE31B0921C}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_uncovered.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{650E8E2EF0218F7E}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{650E8E2EF0218F78}" {
       m_eSlotTypes 24
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{650E8E2E00FB15C1}" {
   m_sIdentifier "Helicopters"
  }
 }
}