SCR_EntityCatalogMultiList : "{09C2ED5F617A0390}Configs/EntityCatalog/USSR/Vehicles_EntityCatalog_USSR.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{5D2348260FAC0091}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F486BE7B532C}" {
       m_eValidEditorModes EDIT
      }
      SCR_EntityCatalogSpawnerData "{5D247327E1AF547A}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{650CFB6355E0684E}" {
     m_sEntityPrefab "{E171C9F443958371}Prefabs/MP/Campaign/Assets/CampaignMobileAssemblyEast.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6064E51CC8B32FED}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6064E51CF6673D6B}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}