SCR_LoadoutSaveBlackListHolder {
 m_LoadoutSaveBlackLists {
  SCR_LoadoutSaveBlackList "{657B3576C768658B}" {
   m_bBlackListActive 1
   m_UIInfo SCR_UIInfo "{657B3576E1FD1A68}" {
    Name "#AR-ArsenalItemType_WeaponAttachment_Name FLIR"
    Icon "{CB055708E982C0A5}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Optics.edds"
   }
   m_aBlackListedPrefabs {
    "{3A4E2F9091E70EC7}Prefabs/Weapons/Attachments/Optics/infratech1tws/Optic_Infratech1tws.et"
    "{1A8E5E21EC65EE58}Prefabs/Weapons/Attachments/Optics/reap_ir/reap_ir.et"
    "{09F49104A6C4558B}Prefabs/Weapons/Attachments/Optics/pas13g/Optic_Thermal_pas13g_m4m16.et"
    "{8650539567168155}Prefabs/Weapons/Attachments/Optics/pas13g/Optic_Thermal_pas13g_mdo.et"
    "{A70369D9AB61DBD1}Prefabs/Weapons/Attachments/Optics/pas13g/Optic_Thermal_pas13g_ts30a2.et"
    "{F30B5EEADDEFCD43}Prefabs/Weapons/Attachments/Optics/reap_ir/snipe_ir.et"
    "{085AB57005296E19}Prefabs/Weapons/Attachments/Optics/reap_ir/snipe_ir_acog.et"
    "{22E51EE7DB41E2F0}Prefabs/Weapons/Attachments/Optics/reap_ir/snipe_ir_m40.et"
    "{2B10341C641EC041}Prefabs/Items/Equipment/Thermals/PATROL_IR/Thermal_PatrolIr.et"
   }
  }
 }
}