SCR_XPRewardList : "{E6FC4537B53EA00B}Configs/Campaign/XPRewards.conf" {
 m_aRewardList {
  SCR_XPRewardInfo "{51BC713E81C18CF3}" {
   m_iRewardXP 40
  }
  SCR_XPRewardInfo "{51C6A3459A34BAE8}" {
   m_iRewardXP 40
  }
  SCR_XPRewardInfo "{5E0E812547C995B6}" {
   m_iRewardXP -25
  }
  SCR_XPRewardInfo "{652E9455800AF630}" {
   m_eRewardID RELAY_RECONFIGURED
   m_sRewardName "#AR-Campaign_XPReward_RelayReconfigured"
   m_iRewardXP 100
  }
  SCR_XPRewardInfo "{652E9455800AF634}" {
   m_eRewardID BASE_SEIZED
   m_sRewardName "#AR-Campaign_XPReward_BaseSeized"
   m_iRewardXP 200
  }
  SCR_XPRewardInfo "{652E9455800AF635}" {
   m_eRewardID SUPPLIES_DELIVERED
   m_sRewardName "#AR-Campaign_XPReward_SuppliesDelivered"
   m_iRewardXP 150
  }
  SCR_XPRewardInfo "{652E9455800AF637}" {
   m_eRewardID SUPPORT_EVAC
   m_sRewardName "#AR-Campaign_XPReward_SupportProvided"
   m_iRewardXP 50
  }
  SCR_XPRewardInfo "{652E9455800AF628}" {
   m_eRewardID SUPPORT_FUEL
   m_sRewardName "#AR-Campaign_XPReward_SupportProvided"
   m_iRewardXP 50
  }
  SCR_XPRewardInfo "{652E9455800AF629}" {
   m_eRewardID TASK_DEFEND
   m_sRewardName "#AR-Campaign_XPReward_BaseDefended"
   m_iRewardXP 75
  }
  SCR_XPRewardInfo "{652E9455800AF62A}" {
   m_eRewardID SERVICE_BUILD
   m_sRewardName "#AR-Campaign_Hint_Building_Title"
   m_iRewardXP 35
  }
  SCR_XPRewardInfo "{652E9455800AF62B}" {
   m_eRewardID BASE_DEFENDED
   m_sRewardName "#AR-Campaign_XPReward_BaseDefended"
   m_iRewardXP 25
  }
  SCR_XPRewardInfo "{652E9455800AF62C}" {
   m_eRewardID CUSTOM_1
   m_sRewardName ""
   m_iRewardXP 20
   m_bAllowNotification 0
  }
  SCR_XPRewardInfo "{652E9455800AEF18}" {
   m_eRewardID SPAWN_PROVIDER
   m_sRewardName "#AR-Campaign_XPReward_RadioSpawn"
   m_iRewardXP 15
  }
  SCR_XPRewardInfo "{652E9455800AEF1A}" {
   m_eRewardID FREE_ROAM_BUILDING_BUILT
   m_sRewardName "#AR-Campaign_Hint_Building_Title"
   m_iRewardXP 20
  }
  SCR_XPRewardInfo "{652E9455800AEF14}" {
   m_eRewardID VALUABLE_INTEL_HANDIN_SMALL
   m_sRewardName "#AR-XPReward_Intel_Small"
   m_iRewardXP 5
  }
  SCR_XPRewardInfo "{652E9455800AEF15}" {
   m_eRewardID VALUABLE_INTEL_HANDIN_MEDIUM
   m_sRewardName "#AR-XPReward_Intel_Medium"
  }
  SCR_XPRewardInfo "{652E9455800AEEF2}" {
   m_eRewardID VALUABLE_INTEL_HANDIN_LARGE
   m_sRewardName "#AR-XPReward_Intel_Large"
   m_iRewardXP 20
  }
 }
}