SCR_CampaignFaction : "{ADFDBDA163950168}Configs/Factions/US_Campaign.conf" {
 UIInfo SCR_FactionUIInfo "{528C961236B7DCD3}" {
  Name "#RHS-Faction_USAF"
  Icon "{9415F1FFF6591F8D}UI/Textures/Editor/EditableEntities/Factions/USAF_icon.edds"
  m_sNameUpper "#RHS-Faction_USAF"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{A6B5C067D402534A}Configs/EntityCatalog/US/Vehicles_EntityCatalog_US_Podval_2.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{2B0ED82B7F2B2CF8}Configs/EntityCatalog/USMC/USMC_InventoryItems_Podval.conf" {
  }
 }
 m_aStartingVehicles {
  "{F1FBD0972FA5FE09}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport.et"
  "{46E2C84AFFC3708B}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF_Podval.et"
  "{46E2C84AFFC3708B}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF_Podval.et"
 }
}