SCR_CampaignFaction : "{ADFDBDA163950168}Configs/Factions/US_Campaign.conf" {
 UIInfo SCR_FactionUIInfo "{528C961236B7DCD3}" {
  Name "#RHS-Faction_USAF"
  Icon "{9415F1FFF6591F8D}UI/Textures/Editor/EditableEntities/Factions/USAF_icon.edds"
  m_sNameUpper "#RHS-Faction_USAF"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{6056BD5F6A436153}" {
     m_aEntities {
      SCR_EntityCatalogEntry "{5DF69575F4160EE2}" {
       m_sEntityPrefab "{CF92A72294E5BFD6}Prefabs/Characters/Campaign/us_army/MC/Campaign_US_Player_Podval_ACU1_MC.et"
      }
      SCR_EntityCatalogEntry "{656748CC35558EBF}" {
       m_sEntityPrefab "{42329A924424969B}Prefabs/Characters/Campaign/us_army/Campaign_US_Player_Podval_ACU1_UCP.et"
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{A6B5C067D402534A}Configs/EntityCatalog/US/Vehicles_EntityCatalog_US_Podval_2.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{2B0ED82B7F2B2CF8}Configs/EntityCatalog/USMC/USMC_InventoryItems_Podval.conf" {
  }
 }
 m_aStartingVehicles {
  "{F1FBD0972FA5FE09}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport.et"
  "{46E2C84AFFC3708B}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF_Podval.et"
  "{46E2C84AFFC3708B}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF_Podval.et"
 }
 m_MobileHQPrefab "{DF74DF83617182F0}Prefabs/MP/Campaign/Assets/CampaignMobileAssemblyWest_Podval.et"
}