SCR_MissionHeaderCampaign : "{94992A3D7CE4FF8A}Missions/23_Campaign_Western.conf" {
 World "{1A56D1C3DFBC852D}Worlds/WesternEveron_PodvalConflict/WesternEveron_PodvalConflict.ent"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
}