SCR_MissionHeaderCampaign : "{FDE33AFE2ED7875B}Missions/23_Campaign_Montignac.conf" {
 World "{43F83FF96A604490}Worlds/EdenMontignac_PodvalConflict/EdenMontignac_PodvalConflict.ent"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
}