SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" {
 World "{A941113256708DE1}Worlds/Anizay_city_PodvalConflict/Anizay_city_PodvalConflict.ent"
 m_sName "Anizay Podval Conflict"
 m_sAuthor "Bell"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_iPlayerCount 128
 m_sSaveFileName "CTI_CampaignPodval_Anizay"
 m_fXpMultiplier 1.25
}