SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" {
 World "{0D3B61ACAA048FFE}Worlds/Takistan_Central_PodvalConflict/Takistan_Central_PodvalConflict.ent"
 m_sName "Takistan Podval Conflict"
 m_sAuthor "Bell"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_iPlayerCount 128
 m_sSaveFileName "CTI_CampaignPodval_Takistan_Central"
 m_fXpMultiplier 1.25
}