SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" {
 World "{21EAD7183E80DF28}Worlds/Takistan_PodvalConflict/Takistan_PodvalConflict.ent"
 m_sName "Takistan Podval Conflict"
 m_sAuthor "Drongo"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_iPlayerCount 128
 m_sSaveFileName "CTI_CampaignPodval_Barzan"
}