SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" {
 World "{E4BC641656634677}Worlds/Zargabad_PodvalConflict/Zargabad_PodvalConflict.ent"
 m_sName "Zargabad Podval Conflict"
 m_sAuthor "Drongo"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sSaveFileName "CTI_CampaignPodval_Barzan"
}