StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62168CF68AC2F106}" {
   Id "DRG_Base_CalvaryHill"
   Target_en_us "Calvary Hill"
   Target_ru_ru "Холм крёстных мук"
   Modified 1645654046
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF57F70E85B}" {
   Id "DRG_Base_CalvaryHill_U"
   Target_en_us "CALVARRY HILL"
   Target_ru_ru "ХОЛМ КРЁСТНЫХ МУК"
   Modified 1645654072
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF603AF01D2}" {
   Id "DRG_Base_Crossroads"
   Target_en_us "Crossroads"
   Target_ru_ru "Перекрёсток"
   Modified 1645653573
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF6D1258971}" {
   Id "DRG_Base_Crossroads_U"
   Target_en_us "CROSSROADS"
   Target_ru_ru "ПЕРЕКРЁСТОК"
   Modified 1645653652
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF5B9C63D0A}" {
   Id "DRG_Base_OldRuins"
   Target_en_us "Old ruins"
   Target_ru_ru "Старые руины"
   Modified 1645654408
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF5A4BF1821}" {
   Id "DRG_Base_OldRuins_U"
   Target_en_us "OLD RUINS"
   Target_ru_ru "СТАРЫЕ РУИНЫ"
   Modified 1645654451
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF43841E36A}" {
   Id "DRG_Base_RoadblockA"
   Target_en_us "Roadblock alpha"
   Target_ru_ru "Блокпост альфа"
   Modified 1645654676
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF409AA91B0}" {
   Id "DRG_Base_RoadblockA_U"
   Target_en_us "ROADBLOCK ALPHA"
   Target_ru_ru "БЛОКПОСТ АЛЬФА"
   Modified 1645654729
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF4D988A286}" {
   Id "DRG_Base_RoadblockB"
   Target_en_us "Roadblock bravo"
   Target_ru_ru "Блокпост браво"
   Modified 1645654832
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CF4C6184DD6}" {
   Id "DRG_Base_RoadblockB_U"
   Target_en_us "ROADBLOCK BRAVO"
   Target_ru_ru "БЛОКПОСТ БРАВО"
   Modified 1645654854
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62168CFD4CD13C54}" {
   Id "DRG_FrontlineMissionConflict"
   Target_en_us "Everon Frontline"
   Target_ru_ru "Эверон передовая"
   Modified 1645658693
   Author "hasta"
   LastChanged "hasta"
  }
 }
}